language: csharp
mono: none
dotnet: 3.1

os:
  - linux
  - osx

osx_image: xcode8.3
  
before_install:  
  - if test "$TRAVIS_OS_NAME" == "osx"; then ulimit -n 2048; fi
  
before_script:
  - dotnet restore

script:
  - dotnet test test/stashbox.tests.csproj -c Release -f netcoreapp2.0
  - dotnet test test/stashbox.tests.csproj -c Release -f netcoreapp3.1

notifications:
  slack:
    secure: V6cvLeezoKCm6C9SnpzieHIelUVjCDK0AbdCgB+DSxiaD5yGqOdsXK7zOVwAnMJ6dI/GbBDOo+w4xYZhjWh5+8UaChH5DWJwbepcWbTKX4foMZvrzJp0Ju+Gn0UJUiCeWcZ+bMqzX9jAkVV+QfglSKMMu3POWjxOSKcZqg5TkDeC8F2WgkaJjQacJz7MWpKxC2xucG+qeowK+Z4DOa3nVYaepEMFef7IwPi55J7xjLtzOXfSDbCaQMUG2LaoYNAN+sMXili1non+vdZYiSFkPeeXredKopZdzzeh70EUfreJ+AqjZRyXBKre+yXVvofHlo9b4GX5TtXLiCdAy77vxVvnGeedSMBfP5IQ5efXu4xZ1nWx5hSNiySPDHyFXPFdYxVWonr6ymj/oLvOX6W3HZRCllqw8W3dL2Y9tsZB8JXIlk3ar9gKH6f8JL5NX8/dLkf4GWL0miGQWcpzXWV8ru+AEHGIDO+fqE1WJ8WnnZ+n/bif9WKYeQwc+BbqSzVUdjTTj/CQ1PAHkgyQl7N9V0hO9GPekFT7NNhJ/flRrTS6hN4u5pYF+x20LZS926MxGT4VXVJChukAyMIL7basscKm6143gGj3B+LsSW4+V4vpGe1/CkNjDZe432TjgbeaeTMcugA7Ct8F3yf7VAmpOOcP5lPmDnC5Q8ritS8z5eg=
