environment:
  github_auth_token:
    secure: z/dKTRVRPmpItPTM/lYdX7dBJk3roDLV98Uj1XzpDqqV868xhHX8dnyKwPAJooUj
  sonarqube_token:
    secure: +1HWbXdBJr2pRiVYPjXzHOhz7bH35FHd18F+VxQHeWdzOK7uAXEt88tResk6Ku3I
  build_version: ''

deploy:
- provider: NuGet
  api_key:
    secure: reeMv8YSGs2hypmjbqAl5z0mxm4QBgHRYsnSwsYUXJZ76begJoSdg51CWGFyBPgt
  on:
    branch: master

skip_tags: true

image: Visual Studio 2022

configuration: Release

install:
- set JAVA_HOME=C:\Program Files\Java\jdk16
- set PATH=%JAVA_HOME%\bin;%PATH%
- ps: |
    $env:build_version = Get-Content ".version"
    Update-AppveyorBuild -Version "$env:build_version-preview-$env:appveyor_build_number"
    dotnet tool install -g dotnet-sonarscanner
    dotnet tool install -g InheritDocTool

before_build:
- ps: . .\patch-version.ps1 "src\stashbox.csproj" $env:build_version $env:appveyor_build_version
- msbuild /t:Restore /p:Configuration=%configuration% stashbox.sln

build_script:
- ps: if (-Not $env:appveyor_pull_request_number) { dotnet sonarscanner begin /k:"stashbox" /d:"sonar.exclusions=test/**" /d:"sonar.host.url=https://sonarcloud.io" /d:"sonar.login=$env:sonarqube_token" /o:"z4kn4fein-github" /v:$env:appveyor_build_version }
- msbuild /t:Build /p:Configuration=%configuration% /p:ContinuousIntegrationBuild=true stashbox.sln
- ps: if (-Not $env:appveyor_pull_request_number) { dotnet sonarscanner end /d:"sonar.login=$env:sonarqube_token" }

after_build:
- inheritdoc -o
- msbuild /t:Pack /p:IncludeSymbols=true /p:Configuration=%configuration% /p:PackageOutputPath=..\artifacts src\stashbox.csproj

test_script:
- dotnet test test\stashbox.tests.csproj -f net452 -c %configuration% --no-build
- dotnet test test\stashbox.tests.csproj -f netcoreapp3.1 -c %configuration% --no-build
- dotnet test test\stashbox.tests.csproj -f net5.0 -c %configuration% --no-build
- dotnet test test\stashbox.tests.csproj -f net6.0 -c %configuration% --no-build

after_test:
- ps: . .\set-debug-type.ps1 "src\stashbox.csproj"
- ps: . .\coverage.ps1

artifacts:
  - path: artifacts\Stashbox.*.nupkg
    name: NuGet Packages
  - path: artifacts\Stashbox.*.snupkg
    name: NuGet Symbol Packages

notifications:
- provider: Email
  to:
  - peter.csajtai@outlook.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true

- provider: Slack
  auth_token:
    secure: /KAOQIEOWc7w1EUl6J01qNam+f+ujntrwh53yJ0zg4qRWsdfWbkjKP2UG7tQDW7/hSVJHqF7Hz/IPdS6Cp5ilsfgH6xYroLB/sawQ/pdC5k=
  channel: '#ci'