deploy:
- provider: NuGet
  api_key:
    secure: doqtwSE1NadH7pf4jqYifDu4tcXzsNiJtPWOccnbUrhSnIJX+5js7m8z+kV9LNJ2

- provider: NuGet
  server: https://nuget.pkg.github.com/z4kn4fein/index.json
  artifact: /.nupkg/
  username: z4kn4fein
  api_key:
    secure: TaIug8cHioxT2qDznFpGtDinZiDi+20pEMQZUVAATWCvGLG9Y5LrjaxDUQtGyt38

- provider: GitHub
  tag: $(build_version)
  release: Stashbox v$(build_version)
  auth_token:
    secure: TaIug8cHioxT2qDznFpGtDinZiDi+20pEMQZUVAATWCvGLG9Y5LrjaxDUQtGyt38
  artifact: /.*\.nupkg|.*\.snupkg/

environment:
  build_version: ''

image: Visual Studio 2019

configuration: Release

install:
- ps: |
    $env:build_version = Get-Content ".version"
    Update-AppveyorBuild -Version "$env:build_version-$env:appveyor_build_number"
    dotnet tool install -g InheritDocTool

before_build:
- ps: . .\patch-version.ps1 "src\stashbox.csproj" $env:build_version $env:build_version

build_script:
- msbuild /t:Restore /p:Configuration=%configuration% stashbox.sln
- msbuild /t:Build /p:Configuration=%configuration% stashbox.sln

test_script:
- dotnet test test\stashbox.tests.csproj -f netcoreapp3.1 -c %configuration% --no-build

after_build:
- inheritdoc -o
- msbuild /t:Pack /p:IncludeSymbols=true /p:Configuration=%configuration% /p:PackageOutputPath=..\artifacts src\stashbox.csproj

artifacts:
  - path: artifacts\Stashbox.*.nupkg
    name: NuGet Packages
  - path: artifacts\Stashbox.*.snupkg
    name: NuGet Symbol Packages

notifications:
- provider: Email
  to:
  - peter.csajtai@outlook.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true

- provider: Slack
  auth_token:
    secure: /KAOQIEOWc7w1EUl6J01qNam+f+ujntrwh53yJ0zg4qRWsdfWbkjKP2UG7tQDW7/hSVJHqF7Hz/IPdS6Cp5ilsfgH6xYroLB/sawQ/pdC5k=
  channel: '#stashbox'