environment:
  github_auth_token:
    secure: z/dKTRVRPmpItPTM/lYdX7dBJk3roDLV98Uj1XzpDqqV868xhHX8dnyKwPAJooUj
  sonarqube_token:
    secure: +1HWbXdBJr2pRiVYPjXzHOhz7bH35FHd18F+VxQHeWdzOK7uAXEt88tResk6Ku3I
  build_version: ''

deploy:
- provider: NuGet
  server: https://www.myget.org/F/pcsajtai/api/v2/package
  symbol_server: https://www.myget.org/F/pcsajtai/symbols/api/v2/package
  api_key:
    secure: 2bITagXOj2s3bTJaGXh8/iyWtST8OQOFaMM+0GAKgZts9OjCVCiV7C+E/0SYsM6M

skip_tags: true

image: Visual Studio 2017

configuration: Release

install:
- ps: |
    $env:build_version = Get-Content ".version"
    Update-AppveyorBuild -Version "$env:build_version-preview-$env:appveyor_build_number"
    dotnet tool install -g dotnet-sonarscanner
    dotnet tool install -g InheritDocTool

before_build:
- ps: . .\patch-version.ps1 "src\stashbox.csproj" $env:build_version $env:appveyor_build_version 
- ps: if ($env:appveyor_pull_request_number) { dotnet sonarscanner begin /k:"stashbox" /d:"sonar.host.url=https://sonarcloud.io" /d:"sonar.login=$env:sonarqube_token" /o:"z4kn4fein-github" /d:"sonar.analysis.mode=preview" /d:"sonar.github.pullRequest=$env:APPVEYOR_PULL_REQUEST_NUMBER" /d:"sonar.github.repository=z4kn4fein/stashbox" /d:"sonar.github.oauth=$env:github_auth_token" /v:$env:appveyor_build_version }
- ps: if (-Not $env:appveyor_pull_request_number) { dotnet sonarscanner begin /k:"stashbox" /d:"sonar.host.url=https://sonarcloud.io" /d:"sonar.login=$env:sonarqube_token" /o:"z4kn4fein-github" /v:$env:appveyor_build_version }

build_script:
- msbuild /t:Restore /p:Configuration=%configuration% stashbox.sln
- msbuild /t:Build /p:Configuration=%configuration% stashbox.sln

after_build:
- dotnet sonarscanner end /d:"sonar.login=%sonarqube_token%"
- inheritdoc -o
- msbuild /t:Pack /p:IncludeSymbols=true /p:Configuration=%configuration% /p:PackageOutputPath=..\artifacts src\stashbox.csproj

test_script:
- dotnet test test\stashbox.tests.csproj -f net452 -c %configuration% --no-build
- dotnet test test\stashbox.tests.csproj -f netcoreapp1.0 -c %configuration% --no-build
- dotnet test test\stashbox.tests.csproj -f netcoreapp2.0 -c %configuration% --no-build

after_test:
- ps: . .\set-debug-type.ps1 "src\stashbox.csproj"
- ps: . .\coverage.ps1

artifacts:
- path: artifacts\Stashbox.*.nupkg
  name: NuGet

notifications:
- provider: Email
  to:
  - peter.csajtai@outlook.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true

- provider: Slack
  auth_token:
    secure: /KAOQIEOWc7w1EUl6J01qNam+f+ujntrwh53yJ0zg4qRWsdfWbkjKP2UG7tQDW7/hSVJHqF7Hz/IPdS6Cp5ilsfgH6xYroLB/sawQ/pdC5k=
  channel: '#stashbox'